# Machine Learning Zoomcamp


## 1.7 Introduction to NumPy


Plan:

* Creating arrays
* Multi-dimensional arrays
* Randomly generated arrays
* Element-wise operations
    * Comparison operations
    * Logical operations
* Summarizing operations

In [1]:
import numpy as np

In [34]:
np

<module 'numpy' from '/mnt/data/projects/PycharmProjects/MLZoomcamp/.venv/lib/python3.14/site-packages/numpy/__init__.py'>

## Creating arrays


In [35]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [37]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [38]:
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [39]:
a[2] = 10

In [40]:
a

array([ 1,  2, 10,  5,  7, 12])

In [41]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [42]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dimensional arrays


In [43]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [44]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [45]:
n[0, 1] = 20

In [46]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [47]:
n[2] = [1, 1, 1]

In [48]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [49]:
n[:, 2] = [0, 1, 2]

In [50]:
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

## Randomly generated arrays


In [51]:
np.random.seed(2)
100 * np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [52]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [53]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations


In [54]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [55]:
b = (10 + (a * 2)) ** 2 / 100

In [56]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [57]:
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

## Comparison operations

In [58]:
a

array([0, 1, 2, 3, 4])

In [59]:
a >= 2

array([False, False,  True,  True,  True])

In [60]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [61]:
a > b

array([False, False,  True,  True,  True])

In [62]:
a[a > b]

array([2, 3, 4])

## Summarizing operations

In [63]:
a

array([0, 1, 2, 3, 4])

In [64]:
a.std()

np.float64(1.4142135623730951)

In [65]:
n.min()

np.int64(0)

### Next

Linear algebra refresher

# Dot Product

In [70]:
def vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    res = 0.0
    for i in range(n):
        res += u[i]*v[i]
    return res

In [72]:
u = np.array([2,4,5,6])
v = np.array([1,0,0,2])

vector_multiplication(u,v)

np.float64(14.0)

In [73]:
u.dot(v)

np.int64(14)

# Matrix to Vector Mult

In [81]:
def matrix_vector_mult(u,v):
    assert u.shape[1] == v.shape[0]
    n = u.shape[0]

    res = np.zeros(u.shape[0])
    for i in range(n):
        res[i] += vector_multiplication(u[i],v)
    return res

In [82]:
u = np.array([[2,4,5,6],[1,2,1,2],[3,1,2,1]])
v = np.array([1,0.5,2,1])

matrix_vector_mult(u,v)

array([20. ,  6. ,  8.5])

In [83]:
u.dot(v)

array([20. ,  6. ,  8.5])

# Matrix to Matrix Mult

In [84]:
def matrix_mult(U,V):
    assert U.shape[1] == V.shape[0]

    rows = U.shape[0]
    cols = V.shape[1]

    res = np.zeros((rows,cols))

    for i in range(cols):
        vi = V[:,i]
        Uvi= matrix_vector_mult(U, vi)
        res[:,i] = Uvi
    return res



In [85]:
U = np.array([[2,4,5,6],[1,2,1,2],[3,1,2,1]])
V = np.array([[1,1,2],[0,0.5,1],[0,2,1],[2,1,0]])

matrix_mult(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [88]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

# Identity Matrix

In [89]:
I = np.eye(3)
V = np.array([[1,2,3],[4,5,6],[7,8,9]])

V.dot(I)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [90]:
I.dot(V)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

# Inverse Matrix

In [92]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 3, 1]
])
V_inv = np.linalg.inv(V)
V_inv

array([[ 1. , -2. ,  0. ],
       [ 0. , -0.4,  0.4],
       [ 0. ,  1.2, -0.2]])

In [93]:
V_inv.dot(V)

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 2.77555756e-17, 1.00000000e+00]])